;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		hungry-delete-forward
		indent-for-tab-command
		save-some-buffers
		switch-window
		text-scale-adjust
		upcase-region
		))

(setq mc/cmds-to-run-once
      '(
		hungry-delete-backward
		kill-region
		))
